// ArogyaSetu AI — Demo Data
// All data is synthetic and for demonstration purposes only

const today = new Date();
const formatDate = (d) => d.toISOString().split('T')[0];
const daysAgo = (n) => { const d = new Date(today); d.setDate(d.getDate() - n); return formatDate(d); };
const daysFromNow = (n) => { const d = new Date(today); d.setDate(d.getDate() + n); return formatDate(d); };

export const DEMO_PATIENTS = [
  {
    id: 'P-2026-001',
    name: 'Lakshmi Devi',
    age: 28,
    gender: 'Female',
    phone: '9876XXXX01',
    village: 'Rampur',
    bloodGroup: 'B+',
    isPregnant: true,
    pregnancyWeek: 32,
    edd: daysFromNow(56),
    registeredDate: daysAgo(180),
    lastVisit: daysAgo(7),
    conditions: ['Pregnancy', 'Mild Anemia'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(7), bp: '110/70', pulse: 82, temp: 98.4, weight: 62, spo2: 98, hemoglobin: 10.2 },
      { date: daysAgo(30), bp: '108/68', pulse: 78, temp: 98.6, weight: 60, spo2: 99, hemoglobin: 10.0 },
    ],
    visits: [
      { date: daysAgo(7), type: 'ANC Visit', notes: 'Regular ANC checkup. Vitals normal. Iron supplements continued.', by: 'ASHA Priya' },
      { date: daysAgo(30), type: 'ANC Visit', notes: 'Weight gain on track. BP normal. Advised nutrition.', by: 'ASHA Priya' },
      { date: daysAgo(60), type: 'ANC Visit', notes: 'Ultrasound done. Baby growth normal.', by: 'Dr. Sharma' },
    ],
    prescriptions: [
      { date: daysAgo(7), doctor: 'Dr. Sharma', medicines: [
        { name: 'Iron Folic Acid', dosage: '1 tablet', frequency: 'Once daily', duration: '90 days' },
        { name: 'Calcium', dosage: '500mg', frequency: 'Twice daily', duration: '60 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(60), type: 'Ultrasound', result: 'Normal fetal growth', facility: 'PHC Rampur' },
      { date: daysAgo(90), type: 'Blood Test', result: 'Hemoglobin 10.0 g/dL', facility: 'PHC Rampur' },
    ],
  },
  {
    id: 'P-2026-002',
    name: 'Rajesh Kumar',
    age: 55,
    gender: 'Male',
    phone: '9876XXXX02',
    village: 'Rampur',
    bloodGroup: 'A+',
    isPregnant: false,
    registeredDate: daysAgo(365),
    lastVisit: daysAgo(3),
    conditions: ['Type 2 Diabetes', 'Hypertension'],
    allergies: ['Penicillin'],
    vitals: [
      { date: daysAgo(3), bp: '140/90', pulse: 76, temp: 98.2, weight: 78, spo2: 97, sugar: 180 },
      { date: daysAgo(30), bp: '145/92', pulse: 80, temp: 98.4, weight: 79, spo2: 96, sugar: 200 },
    ],
    visits: [
      { date: daysAgo(3), type: 'Follow-up', notes: 'BP slightly elevated. Sugar 180 fasting. Medication adjusted.', by: 'Dr. Sharma' },
      { date: daysAgo(30), type: 'Regular Checkup', notes: 'Sugar levels high. Diet counseling given.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(3), doctor: 'Dr. Sharma', medicines: [
        { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: '30 days' },
        { name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily', duration: '30 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(30), type: 'Blood Sugar', result: 'Fasting: 200 mg/dL, PP: 280 mg/dL', facility: 'PHC Rampur' },
    ],
  },
  {
    id: 'P-2026-003',
    name: 'Sita Kumari',
    age: 24,
    gender: 'Female',
    phone: '9876XXXX03',
    village: 'Sundernagar',
    bloodGroup: 'O+',
    isPregnant: true,
    pregnancyWeek: 16,
    edd: daysFromNow(168),
    registeredDate: daysAgo(60),
    lastVisit: daysAgo(14),
    conditions: ['Pregnancy'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(14), bp: '106/66', pulse: 74, temp: 98.6, weight: 54, spo2: 99, hemoglobin: 11.5 },
    ],
    visits: [
      { date: daysAgo(14), type: 'ANC Visit', notes: 'First trimester completed. All normal.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(14), doctor: 'Dr. Reddy', medicines: [
        { name: 'Folic Acid', dosage: '5mg', frequency: 'Once daily', duration: '90 days' },
      ]},
    ],
    reports: [],
  },
  {
    id: 'P-2026-004',
    name: 'Ramu Yadav',
    age: 8,
    gender: 'Male',
    phone: '9876XXXX04',
    village: 'Rampur',
    bloodGroup: 'B-',
    isPregnant: false,
    registeredDate: daysAgo(730),
    lastVisit: daysAgo(5),
    conditions: ['Seasonal Fever'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(5), bp: '90/60', pulse: 100, temp: 101.2, weight: 24, spo2: 98 },
    ],
    visits: [
      { date: daysAgo(5), type: 'Sick Visit', notes: 'Fever for 2 days. Mild cough. No rash.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(5), doctor: 'Dr. Sharma', medicines: [
        { name: 'Paracetamol Syrup', dosage: '5ml', frequency: 'Three times daily', duration: '3 days' },
        { name: 'ORS', dosage: '1 packet', frequency: 'As needed', duration: '3 days' },
      ]},
    ],
    reports: [],
  },
  {
    id: 'P-2026-005',
    name: 'Meena Bai',
    age: 62,
    gender: 'Female',
    phone: '9876XXXX05',
    village: 'Sundernagar',
    bloodGroup: 'AB+',
    isPregnant: false,
    registeredDate: daysAgo(500),
    lastVisit: daysAgo(10),
    conditions: ['Hypertension', 'Arthritis'],
    allergies: ['Sulfa drugs'],
    vitals: [
      { date: daysAgo(10), bp: '150/95', pulse: 72, temp: 98.0, weight: 65, spo2: 96 },
    ],
    visits: [
      { date: daysAgo(10), type: 'Follow-up', notes: 'Joint pain persisting. BP elevated. Referred to district hospital.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(10), doctor: 'Dr. Reddy', medicines: [
        { name: 'Enalapril', dosage: '5mg', frequency: 'Once daily', duration: '30 days' },
      ]},
    ],
    reports: [],
  },
  {
    id: 'P-2026-006',
    name: 'Anita Devi',
    age: 30,
    gender: 'Female',
    phone: '9876XXXX06',
    village: 'Rampur',
    bloodGroup: 'A-',
    isPregnant: true,
    pregnancyWeek: 38,
    edd: daysFromNow(14),
    registeredDate: daysAgo(240),
    lastVisit: daysAgo(2),
    conditions: ['Pregnancy', 'Gestational Diabetes'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(2), bp: '120/78', pulse: 86, temp: 98.6, weight: 70, spo2: 98, hemoglobin: 11.0, sugar: 140 },
    ],
    visits: [
      { date: daysAgo(2), type: 'ANC Visit', notes: 'Week 38. GDM controlled. Institutional delivery planned.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(2), doctor: 'Dr. Sharma', medicines: [
        { name: 'Insulin (as prescribed)', dosage: 'As directed', frequency: 'As directed', duration: 'Until delivery' },
        { name: 'Iron Folic Acid', dosage: '1 tablet', frequency: 'Once daily', duration: '30 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(7), type: 'GTT', result: 'Gestational diabetes confirmed', facility: 'District Hospital' },
    ],
  },
  {
    id: 'P-2026-007',
    name: 'Suresh Reddy',
    age: 45,
    gender: 'Male',
    phone: '9876XXXX07',
    village: 'Sundernagar',
    bloodGroup: 'O-',
    isPregnant: false,
    registeredDate: daysAgo(200),
    lastVisit: daysAgo(20),
    conditions: ['Chronic Cough'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(20), bp: '118/76', pulse: 78, temp: 98.8, weight: 68, spo2: 95 },
    ],
    visits: [
      { date: daysAgo(20), type: 'Sick Visit', notes: 'Persistent cough for 3 weeks. Referred for TB screening.', by: 'ASHA Priya' },
    ],
    prescriptions: [],
    reports: [],
  },
  {
    id: 'P-2026-008',
    name: 'Kavitha Prasad',
    age: 35,
    gender: 'Female',
    phone: '9876XXXX08',
    village: 'Rampur',
    bloodGroup: 'B+',
    isPregnant: false,
    registeredDate: daysAgo(100),
    lastVisit: daysAgo(1),
    conditions: ['Seasonal Allergy'],
    allergies: ['Dust'],
    vitals: [
      { date: daysAgo(1), bp: '110/70', pulse: 72, temp: 98.4, weight: 58, spo2: 99 },
    ],
    visits: [
      { date: daysAgo(1), type: 'Sick Visit', notes: 'Nasal congestion, sneezing. Seasonal allergy.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(1), doctor: 'Dr. Reddy', medicines: [
        { name: 'Cetirizine', dosage: '10mg', frequency: 'Once daily', duration: '5 days' },
      ]},
    ],
    reports: [],
  },
  {
    id: 'P-2026-009',
    name: 'Kavya Patel',
    age: 28,
    gender: 'Female',
    phone: '9876XXXX09',
    village: 'Sundernagar',
    bloodGroup: 'O+',
    isPregnant: false,
    registeredDate: daysAgo(45),
    lastVisit: daysAgo(5),
    conditions: ['General Wellness'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(5), bp: '118/76', pulse: 74, temp: 98.4, weight: 58, spo2: 99 },
    ],
    visits: [
      { date: daysAgo(5), type: 'Field Registration', notes: 'Community health survey intake. Vitals normal.', by: 'ASHA Priya' },
    ],
    prescriptions: [],
    reports: [],
  },
  {
    id: 'P-2026-010',
    name: 'Manjula Gowda',
    age: 26,
    gender: 'Female',
    phone: '9876XXXX10',
    village: 'Rampur',
    bloodGroup: 'AB-',
    isPregnant: true,
    pregnancyWeek: 28,
    edd: daysFromNow(84),
    registeredDate: daysAgo(120),
    lastVisit: daysAgo(2),
    conditions: ['High-Risk Pregnancy', 'Severe Anemia'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(2), bp: '100/62', pulse: 92, temp: 98.4, weight: 51, spo2: 97, hemoglobin: 7.8 },
      { date: daysAgo(30), bp: '104/64', pulse: 88, temp: 98.6, weight: 50, spo2: 98, hemoglobin: 8.4 },
    ],
    visits: [
      { date: daysAgo(2), type: 'High-Risk ANC', notes: 'Severe pallor observed. Hb dropped to 7.8 g/dL. Emergency iron sucrose infusion recommended at PHC.', by: 'ASHA Priya' },
      { date: daysAgo(30), type: 'ANC Visit', notes: 'Dietary intake reviewed. Double dose IFA provided.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(2), doctor: 'Dr. Sharma', medicines: [
        { name: 'Iron Sucrose IV', dosage: '200mg in 100ml NS', frequency: 'Alternate days (2 doses)', duration: '4 days' },
        { name: 'Calcium + Vit D3', dosage: '500mg', frequency: 'Twice daily', duration: '60 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(2), type: 'CBC Report', result: 'Hb: 7.8 g/dL, Microcytic Hypochromic Anemia', facility: 'PHC Rampur' },
    ],
  },
  {
    id: 'P-2026-011',
    name: 'Balram Singh',
    age: 68,
    gender: 'Male',
    phone: '9876XXXX11',
    village: 'Chandanpur',
    bloodGroup: 'B+',
    isPregnant: false,
    registeredDate: daysAgo(300),
    lastVisit: daysAgo(4),
    conditions: ['COPD', 'Hypertension'],
    allergies: ['Aspirin'],
    vitals: [
      { date: daysAgo(4), bp: '158/94', pulse: 84, temp: 98.2, weight: 64, spo2: 91 },
      { date: daysAgo(45), bp: '150/90', pulse: 80, temp: 98.6, weight: 65, spo2: 93 },
    ],
    visits: [
      { date: daysAgo(4), type: 'Chronic Review', notes: 'Shortness of breath on mild exertion. SpO2 91% on room air. Bronchial wheezing noted.', by: 'Dr. Sharma' },
    ],
    prescriptions: [
      { date: daysAgo(4), doctor: 'Dr. Sharma', medicines: [
        { name: 'Salbutamol Inhaler', dosage: '100mcg (2 puffs)', frequency: 'SOS / Thrice daily', duration: '30 days' },
        { name: 'Telmisartan', dosage: '40mg', frequency: 'Once daily (morning)', duration: '30 days' },
        { name: 'Budesonide Rotacaps', dosage: '200mcg', frequency: 'Twice daily', duration: '30 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(45), type: 'Chest X-Ray', result: 'Hyperinflated lung fields, no active infiltrates', facility: 'District Hospital' },
    ],
  },
  {
    id: 'P-2026-012',
    name: 'Ananya Sharma',
    age: 4,
    gender: 'Female',
    phone: '9876XXXX12',
    village: 'Rampur',
    bloodGroup: 'A+',
    isPregnant: false,
    registeredDate: daysAgo(150),
    lastVisit: daysAgo(6),
    conditions: ['Moderate Malnutrition (MAM)', 'Recurrent URI'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(6), bp: '92/60', pulse: 98, temp: 98.4, weight: 11.2, spo2: 99 },
    ],
    visits: [
      { date: daysAgo(6), type: 'Nutrition Assessment', notes: 'MUAC: 12.1 cm (Yellow band). Energy-dense nutritional supplement (EDNS) provided. Mother counseled on protein-rich local foods.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(6), doctor: 'Dr. Reddy', medicines: [
        { name: 'Multivitamin Syrup', dosage: '5ml', frequency: 'Once daily', duration: '30 days' },
        { name: 'Albendazole Suspension', dosage: '400mg (10ml)', frequency: 'Single dose stat', duration: '1 day' },
      ]},
    ],
    reports: [],
  },
  {
    id: 'P-2026-013',
    name: 'Govind Das',
    age: 52,
    gender: 'Male',
    phone: '9876XXXX13',
    village: 'Belgaon',
    bloodGroup: 'O+',
    isPregnant: false,
    registeredDate: daysAgo(90),
    lastVisit: daysAgo(3),
    conditions: ['Suspected Pulmonary TB', 'Weight Loss'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(3), bp: '112/72', pulse: 82, temp: 99.8, weight: 52, spo2: 96 },
    ],
    visits: [
      { date: daysAgo(3), type: 'TB Outreach', notes: 'Productive cough for 3+ weeks, low grade evening pyrexia, 4kg weight loss. Sputum collected for CBNAAT (GeneXpert).', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(3), doctor: 'Dr. Sharma', medicines: [
        { name: 'Amoxicillin-Clavulanate', dosage: '625mg', frequency: 'Twice daily', duration: '5 days' },
        { name: 'Paracetamol', dosage: '500mg', frequency: 'SOS', duration: '5 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(3), type: 'CBNAAT Sputum', result: 'Pending laboratory analysis at District TB Centre', facility: 'District TB Centre' },
    ],
  },
  {
    id: 'P-2026-014',
    name: 'Radha Bai',
    age: 42,
    gender: 'Female',
    phone: '9876XXXX14',
    village: 'Sundernagar',
    bloodGroup: 'B+',
    isPregnant: false,
    registeredDate: daysAgo(210),
    lastVisit: daysAgo(8),
    conditions: ['Type 2 Diabetes', 'Diabetic Neuropathy'],
    allergies: ['Ciprofloxacin'],
    vitals: [
      { date: daysAgo(8), bp: '132/84', pulse: 76, temp: 98.6, weight: 66, spo2: 98, sugar: 220 },
      { date: daysAgo(40), bp: '136/86', pulse: 78, temp: 98.4, weight: 67, spo2: 97, sugar: 245 },
    ],
    visits: [
      { date: daysAgo(8), type: 'NCD Follow-up', notes: 'Burning sensation and numbness in bilateral soles. Fasting blood sugar 220 mg/dL. Foot inspection performed - no ulcers.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(8), doctor: 'Dr. Sharma', medicines: [
        { name: 'Metformin', dosage: '850mg', frequency: 'Twice daily (after meals)', duration: '30 days' },
        { name: 'Glimepiride', dosage: '1mg', frequency: 'Once daily (before breakfast)', duration: '30 days' },
        { name: 'Pregabalin + Methylcobalamin', dosage: '75mg/1500mcg', frequency: 'Once daily at bedtime', duration: '30 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(8), type: 'HbA1c', result: 'HbA1c: 8.9% (Poorly controlled)', facility: 'PHC Rampur' },
    ],
  },
  {
    id: 'P-2026-015',
    name: 'Vikram Meena',
    age: 19,
    gender: 'Male',
    phone: '9876XXXX15',
    village: 'Kalyanpur',
    bloodGroup: 'A-',
    isPregnant: false,
    registeredDate: daysAgo(80),
    lastVisit: daysAgo(1),
    conditions: ['Acute Falciparum Malaria', 'High Fever'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(1), bp: '110/68', pulse: 108, temp: 103.4, weight: 58, spo2: 97 },
    ],
    visits: [
      { date: daysAgo(1), type: 'Emergency Sick Call', notes: 'Acute onset rigors and high fever. Bivalent RDT positive for Plasmodium Falciparum. Immediate ACT administered.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(1), doctor: 'Dr. Sharma', medicines: [
        { name: 'Artesunate + Lumefantrine (ACT)', dosage: 'Full adult blister pack', frequency: 'As per NVBDCP schedule', duration: '3 days' },
        { name: 'Primaquine', dosage: '45mg single dose', frequency: 'Day 2', duration: '1 day' },
        { name: 'Paracetamol', dosage: '650mg', frequency: 'Every 6 hours SOS', duration: '3 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(1), type: 'Malaria RDT Card', result: 'Positive for P. falciparum (Pf band present)', facility: 'Sub-Centre Kalyanpur' },
    ],
  },
  {
    id: 'P-2026-016',
    name: 'Shanti Devi',
    age: 31,
    gender: 'Female',
    phone: '9876XXXX16',
    village: 'Rampur',
    bloodGroup: 'O+',
    isPregnant: false,
    registeredDate: daysAgo(280),
    lastVisit: daysAgo(3),
    conditions: ['Post-Partum PNC Care', 'Lactation Counseling'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(3), bp: '116/74', pulse: 78, temp: 98.4, weight: 61, spo2: 99, hemoglobin: 11.2 },
    ],
    visits: [
      { date: daysAgo(3), type: 'PNC Day 14 Visit', notes: 'Institutional delivery at CHC 14 days ago. Baby birth weight 2.8kg. Umbilical cord clean, dry. Exclusive breastfeeding established.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(3), doctor: 'Dr. Sharma', medicines: [
        { name: 'Iron Folic Acid (PNC)', dosage: '1 tablet', frequency: 'Once daily', duration: '180 days' },
        { name: 'Calcium', dosage: '500mg', frequency: 'Twice daily', duration: '180 days' },
      ]},
    ],
    reports: [],
  },
  {
    id: 'P-2026-017',
    name: 'Devendra Yadav',
    age: 60,
    gender: 'Male',
    phone: '9876XXXX17',
    village: 'Sitapur',
    bloodGroup: 'B+',
    isPregnant: false,
    registeredDate: daysAgo(400),
    lastVisit: daysAgo(7),
    conditions: ['Coronary Artery Disease', 'Hypertension'],
    allergies: ['Iodine contrast'],
    vitals: [
      { date: daysAgo(7), bp: '162/98', pulse: 74, temp: 98.2, weight: 75, spo2: 96 },
    ],
    visits: [
      { date: daysAgo(7), type: 'Emergency Referral Review', notes: 'Retrosternal heaviness on walking up slope. Relieved by rest. ECG done at PHC showed ST depression in V4-V6.', by: 'Dr. Sharma' },
    ],
    prescriptions: [
      { date: daysAgo(7), doctor: 'Dr. Sharma', medicines: [
        { name: 'Aspirin', dosage: '75mg', frequency: 'Once daily', duration: '90 days' },
        { name: 'Atorvastatin', dosage: '40mg', frequency: 'Once daily at bedtime', duration: '90 days' },
        { name: 'Metoprolol Succinate', dosage: '25mg', frequency: 'Once daily', duration: '90 days' },
        { name: 'Sorbitrate', dosage: '5mg sublingual', frequency: 'SOS for chest pain', duration: '30 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(7), type: '12-Lead ECG', result: 'Ischemic ST-T changes in lateral leads', facility: 'PHC Rampur' },
    ],
  },
  {
    id: 'P-2026-018',
    name: 'Pooja Verma',
    age: 22,
    gender: 'Female',
    phone: '9876XXXX18',
    village: 'Sundernagar',
    bloodGroup: 'A+',
    isPregnant: true,
    pregnancyWeek: 12,
    edd: daysFromNow(196),
    registeredDate: daysAgo(20),
    lastVisit: daysAgo(4),
    conditions: ['Primigravida', 'Morning Sickness'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(4), bp: '108/68', pulse: 76, temp: 98.6, weight: 49, spo2: 99, hemoglobin: 11.8 },
    ],
    visits: [
      { date: daysAgo(4), type: 'First Trimester ANC', notes: 'First pregnancy registered. Mother and Child Protection (MCP) card issued. Td-1 injection administered.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(4), doctor: 'Dr. Reddy', medicines: [
        { name: 'Folic Acid', dosage: '5mg', frequency: 'Once daily', duration: '30 days' },
        { name: 'Doxylamine + Pyridoxine', dosage: '10mg/10mg', frequency: 'Twice daily as needed', duration: '14 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(4), type: 'First Trimester Ultrasound', result: 'Single live intrauterine gestation, CRL corresponds to 12 weeks', facility: 'Community Health Centre' },
    ],
  },
  {
    id: 'P-2026-019',
    name: 'Chotu Kumar',
    age: 2,
    gender: 'Male',
    phone: '9876XXXX19',
    village: 'Chandanpur',
    bloodGroup: 'B+',
    isPregnant: false,
    registeredDate: daysAgo(180),
    lastVisit: daysAgo(1),
    conditions: ['Acute Diarrhea', 'Mild Dehydration'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(1), bp: '88/56', pulse: 112, temp: 99.2, weight: 10.5, spo2: 98 },
    ],
    visits: [
      { date: daysAgo(1), type: 'Sick Home Visit', notes: 'Watery stools 5 times in 12 hours. Eyes slightly sunken, skin pinch retracts in 1 second. ORS demonstration conducted.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(1), doctor: 'Dr. Sharma', medicines: [
        { name: 'Oral Rehydration Salts (ORS)', dosage: '1 packet in 1 litre water', frequency: 'After every loose stool', duration: '3 days' },
        { name: 'Zinc Sulfate Syrup', dosage: '20mg (5ml)', frequency: 'Once daily', duration: '14 days' },
      ]},
    ],
    reports: [],
  },
  {
    id: 'P-2026-020',
    name: 'Savitri Devi',
    age: 74,
    gender: 'Female',
    phone: '9876XXXX20',
    village: 'Rampur',
    bloodGroup: 'AB+',
    isPregnant: false,
    registeredDate: daysAgo(600),
    lastVisit: daysAgo(9),
    conditions: ['Bilateral Senile Cataract', 'Osteoarthritis'],
    allergies: ['None known'],
    vitals: [
      { date: daysAgo(9), bp: '138/82', pulse: 70, temp: 97.8, weight: 56, spo2: 97 },
    ],
    visits: [
      { date: daysAgo(9), type: 'Geriatric Screening', notes: 'Significant visual impairment in both eyes (counting fingers at 2 metres). Registered for upcoming Block eye surgery camp.', by: 'ASHA Priya' },
    ],
    prescriptions: [
      { date: daysAgo(9), doctor: 'Dr. Reddy', medicines: [
        { name: 'Carboxymethylcellulose Eye Drops', dosage: '1 drop', frequency: 'Four times daily', duration: '30 days' },
        { name: 'Paracetamol', dosage: '650mg', frequency: 'SOS for knee pain', duration: '15 days' },
      ]},
    ],
    reports: [
      { date: daysAgo(9), type: 'Visual Acuity', result: 'Right Eye: 6/60, Left Eye: 3/60 (Mature cataract)', facility: 'PHC Rampur' },
    ],
  },
];

export const DEMO_HEALTH_TICKETS = [
  {
    id: 'HT-2026-000124',
    patientId: 'P-2026-001',
    patientName: 'Lakshmi Devi',
    concern: 'Routine ANC checkup - Week 32',
    priority: 'medium',
    status: 'follow-up-scheduled',
    createdDate: daysAgo(7),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(7), completed: true, note: 'Health ticket created during home visit' },
      { step: 'Symptoms Recorded', date: daysAgo(7), completed: true, note: 'Mild fatigue, back pain' },
      { step: 'Vitals Added', date: daysAgo(7), completed: true, note: 'BP 110/70, Pulse 82' },
      { step: 'Referred', date: daysAgo(7), completed: true, note: 'Referred to PHC for ANC review' },
      { step: 'Doctor Reviewed', date: daysAgo(6), completed: true, note: 'Dr. Sharma reviewed. Continue supplements.' },
      { step: 'Prescription Added', date: daysAgo(6), completed: true, note: 'Iron and Calcium continued' },
      { step: 'Follow-up Scheduled', date: daysAgo(6), completed: true, note: 'Next visit in 2 weeks' },
    ],
    vitals: { bp: '110/70', pulse: 82, temp: 98.4, weight: 62, spo2: 98 },
    symptoms: 'Mild fatigue, lower back pain. No swelling. No headaches.',
    transcript: 'Patient reports mild tiredness and lower back pain since last week.',
    translatedTranscript: null,
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000125',
    patientId: 'P-2026-002',
    patientName: 'Rajesh Kumar',
    concern: 'Elevated blood sugar and blood pressure',
    priority: 'high',
    status: 'doctor-reviewed',
    createdDate: daysAgo(3),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(3), completed: true, note: 'Health ticket created' },
      { step: 'Symptoms Recorded', date: daysAgo(3), completed: true, note: 'Dizziness, frequent urination' },
      { step: 'Vitals Added', date: daysAgo(3), completed: true, note: 'BP 140/90, Sugar 180' },
      { step: 'Referred', date: daysAgo(3), completed: true, note: 'Urgent referral to PHC' },
      { step: 'Doctor Reviewed', date: daysAgo(2), completed: true, note: 'Medication adjusted by Dr. Sharma' },
      { step: 'Prescription Added', date: daysAgo(2), completed: true, note: 'Metformin and Amlodipine prescribed' },
      { step: 'Follow-up Scheduled', date: daysAgo(2), completed: false, note: '' },
    ],
    vitals: { bp: '140/90', pulse: 76, temp: 98.2, weight: 78, spo2: 97, sugar: 180 },
    symptoms: 'Dizziness in morning, increased urination, occasional blurred vision.',
    transcript: 'Subah se chakkar aa raha hai, baar baar bathroom jaana pad raha hai.',
    translatedTranscript: 'Feeling dizzy since morning, frequent urination.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000126',
    patientId: 'P-2026-004',
    patientName: 'Ramu Yadav',
    concern: 'Fever for 2 days with mild cough',
    priority: 'medium',
    status: 'prescription-added',
    createdDate: daysAgo(5),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(5), completed: true, note: 'Child brought by mother' },
      { step: 'Symptoms Recorded', date: daysAgo(5), completed: true, note: 'Fever, mild cough, no rash' },
      { step: 'Vitals Added', date: daysAgo(5), completed: true, note: 'Temp 101.2, Pulse 100' },
      { step: 'Referred', date: daysAgo(5), completed: true, note: 'Referred to PHC' },
      { step: 'Doctor Reviewed', date: daysAgo(4), completed: true, note: 'Viral fever. Symptomatic treatment.' },
      { step: 'Prescription Added', date: daysAgo(4), completed: true, note: 'Paracetamol and ORS' },
      { step: 'Follow-up Scheduled', date: daysAgo(4), completed: false, note: '' },
    ],
    vitals: { bp: '90/60', pulse: 100, temp: 101.2, weight: 24, spo2: 98 },
    symptoms: 'Fever since 2 days, mild dry cough, no rash, appetite reduced.',
    transcript: 'Bacche ko do din se bukhar hai, khansi bhi hai.',
    translatedTranscript: 'Child has fever for 2 days, also has cough.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000127',
    patientId: 'P-2026-005',
    patientName: 'Meena Bai',
    concern: 'Joint pain and elevated blood pressure',
    priority: 'high',
    status: 'referred',
    createdDate: daysAgo(10),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(10), completed: true, note: 'Created during home visit' },
      { step: 'Symptoms Recorded', date: daysAgo(10), completed: true, note: 'Knee and hip pain, headache' },
      { step: 'Vitals Added', date: daysAgo(10), completed: true, note: 'BP 150/95' },
      { step: 'Referred', date: daysAgo(10), completed: true, note: 'Referred to District Hospital' },
      { step: 'Doctor Reviewed', date: null, completed: false, note: '' },
      { step: 'Prescription Added', date: null, completed: false, note: '' },
      { step: 'Follow-up Scheduled', date: null, completed: false, note: '' },
    ],
    vitals: { bp: '150/95', pulse: 72, temp: 98.0, weight: 65, spo2: 96 },
    symptoms: 'Severe joint pain in both knees, difficulty walking, headaches.',
    transcript: 'Ghutno mein bahut dard hai, chal nahi paa rahi hoon.',
    translatedTranscript: 'Severe knee pain, unable to walk properly.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000128',
    patientId: 'P-2026-007',
    patientName: 'Suresh Reddy',
    concern: 'Persistent cough for 3 weeks',
    priority: 'high',
    status: 'referred',
    createdDate: daysAgo(20),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(20), completed: true, note: 'Patient visited ASHA for help' },
      { step: 'Symptoms Recorded', date: daysAgo(20), completed: true, note: 'Persistent cough, weight loss' },
      { step: 'Vitals Added', date: daysAgo(20), completed: true, note: 'SpO2 95%, mild weight loss' },
      { step: 'Referred', date: daysAgo(20), completed: true, note: 'Referred for TB screening at District Hospital' },
      { step: 'Doctor Reviewed', date: null, completed: false, note: '' },
      { step: 'Prescription Added', date: null, completed: false, note: '' },
      { step: 'Follow-up Scheduled', date: null, completed: false, note: '' },
    ],
    vitals: { bp: '118/76', pulse: 78, temp: 98.8, weight: 68, spo2: 95 },
    symptoms: 'Cough for 3 weeks, some weight loss, night sweats occasionally.',
    transcript: 'Moodu vaaraalugaa daggu vastundi, baruvu thaggutundi.',
    translatedTranscript: 'Cough for 3 weeks, losing weight.',
    detectedLanguage: 'Telugu',
  },
  {
    id: 'HT-2026-000129',
    patientId: 'P-2026-006',
    patientName: 'Anita Devi',
    concern: 'Week 38 ANC - Gestational Diabetes monitoring',
    priority: 'high',
    status: 'follow-up-scheduled',
    createdDate: daysAgo(2),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(2), completed: true, note: 'Routine ANC visit' },
      { step: 'Symptoms Recorded', date: daysAgo(2), completed: true, note: 'No complaints, GDM controlled' },
      { step: 'Vitals Added', date: daysAgo(2), completed: true, note: 'BP 120/78, Sugar 140' },
      { step: 'Referred', date: daysAgo(2), completed: true, note: 'Continue at District Hospital' },
      { step: 'Doctor Reviewed', date: daysAgo(1), completed: true, note: 'Dr. Sharma: Plan institutional delivery' },
      { step: 'Prescription Added', date: daysAgo(1), completed: true, note: 'Insulin continued' },
      { step: 'Follow-up Scheduled', date: daysAgo(1), completed: true, note: 'Weekly follow-up until delivery' },
    ],
    vitals: { bp: '120/78', pulse: 86, temp: 98.6, weight: 70, spo2: 98, sugar: 140 },
    symptoms: 'No new symptoms. GDM under control with insulin.',
    transcript: 'Sab theek hai, sugar dawai se control mein hai.',
    translatedTranscript: 'Everything fine, sugar controlled with medication.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000130',
    patientId: 'P-2026-010',
    patientName: 'Manjula Gowda',
    concern: 'Severe Anemia in 28-Week Pregnancy (Hb 7.8 g/dL)',
    priority: 'high',
    status: 'referred',
    createdDate: daysAgo(2),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(2), completed: true, note: 'Home visit ANC intake' },
      { step: 'Vitals & Lab Recorded', date: daysAgo(2), completed: true, note: 'Hb 7.8 g/dL detected on digital hemoglobinometer' },
      { step: 'Referred to PHC', date: daysAgo(2), completed: true, note: 'Emergency referral for IV iron sucrose infusion' },
    ],
    vitals: { bp: '100/62', pulse: 92, temp: 98.4, weight: 51, spo2: 97, hemoglobin: 7.8 },
    symptoms: 'Extreme fatigue, dizziness upon standing, breathlessness on climbing stairs.',
    transcript: 'Chaala neerasanga undi, kurchuni lechinappudu thala tirugutondi.',
    translatedTranscript: 'Feeling very weak, getting dizzy when standing up from sitting.',
    detectedLanguage: 'Telugu',
  },
  {
    id: 'HT-2026-000131',
    patientId: 'P-2026-011',
    patientName: 'Balram Singh',
    concern: 'COPD acute exacerbation with nocturnal wheezing',
    priority: 'high',
    status: 'follow-up-scheduled',
    createdDate: daysAgo(4),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(4), completed: true, note: 'Home visit for chronic respiratory check' },
      { step: 'Vitals Added', date: daysAgo(4), completed: true, note: 'SpO2 91% on room air, BP 158/94' },
      { step: 'Doctor Reviewed', date: daysAgo(4), completed: true, note: 'Inhaler dose adjusted with spacer demonstration' },
    ],
    vitals: { bp: '158/94', pulse: 84, temp: 98.2, weight: 64, spo2: 91 },
    symptoms: 'Chest tightness, wheezing sound while breathing, difficulty sleeping flat.',
    transcript: 'Raat ko saans lene mein seeti jaisi aawaz aati hai aur ghutan hoti hai.',
    translatedTranscript: 'At night there is a whistling sound while breathing and feeling suffocated.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000132',
    patientId: 'P-2026-013',
    patientName: 'Govind Das',
    concern: 'Chronic cough for 3+ weeks with evening fever (Suspected TB)',
    priority: 'high',
    status: 'in-review',
    createdDate: daysAgo(3),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(3), completed: true, note: 'ASHA identified symptoms during village round' },
      { step: 'Sputum Sample Collected', date: daysAgo(3), completed: true, note: 'Sent for GeneXpert (CBNAAT) testing' },
      { step: 'Referred to District Centre', date: daysAgo(3), completed: true, note: 'Awaiting laboratory microbiology confirmation' },
    ],
    vitals: { bp: '112/72', pulse: 82, temp: 99.8, weight: 52, spo2: 96 },
    symptoms: 'Persistent productive cough, night sweats, loss of appetite, noticeable weight loss.',
    transcript: 'Teen hafton se balgam wali khansi hai aur raat ko paseena aata hai.',
    translatedTranscript: 'Cough with phlegm for 3 weeks and night sweats.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000133',
    patientId: 'P-2026-015',
    patientName: 'Vikram Meena',
    concern: 'Acute high-grade fever with rigors (RDT Pf Malaria positive)',
    priority: 'high',
    status: 'resolved',
    createdDate: daysAgo(1),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(1), completed: true, note: 'Emergency alert received from family' },
      { step: 'Rapid Diagnostic Test Done', date: daysAgo(1), completed: true, note: 'RDT positive for P. Falciparum' },
      { step: 'Treatment Started', date: daysAgo(1), completed: true, note: 'First dose ACT administered under supervision' },
    ],
    vitals: { bp: '110/68', pulse: 108, temp: 103.4, weight: 58, spo2: 97 },
    symptoms: 'Violent shivering, high fever spike, severe frontal headache, vomiting.',
    transcript: 'Bohat tej kaanp ke bukhar aaya hai, sar phat raha hai.',
    translatedTranscript: 'Very high fever with intense shivering, severe headache.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000134',
    patientId: 'P-2026-017',
    patientName: 'Devendra Yadav',
    concern: 'Exertional retrosternal chest pain with ECG changes',
    priority: 'high',
    status: 'referred',
    createdDate: daysAgo(7),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(7), completed: true, note: 'Patient presented to PHC triage' },
      { step: 'ECG Completed', date: daysAgo(7), completed: true, note: 'Ischemia noted in lateral leads' },
      { step: 'Referred to Cardiology', date: daysAgo(7), completed: true, note: 'Ambulance transfer arranged to District Hospital' },
    ],
    vitals: { bp: '162/98', pulse: 74, temp: 98.2, weight: 75, spo2: 96 },
    symptoms: 'Crushing chest heaviness radiating to left shoulder on walking uphill.',
    transcript: 'Chaati mein bojh lagta hai aur baayein haath mein dard jaata hai.',
    translatedTranscript: 'Heavy sensation in chest radiating to left arm.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000135',
    patientId: 'P-2026-019',
    patientName: 'Chotu Kumar',
    concern: 'Acute watery diarrhea with mild dehydration (Pediatric)',
    priority: 'medium',
    status: 'follow-up-scheduled',
    createdDate: daysAgo(1),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(1), completed: true, note: 'Mother approached ASHA at Anganwadi' },
      { step: 'Dehydration Assessed', date: daysAgo(1), completed: true, note: 'Moderate dehydration, alert child' },
      { step: 'ORS + Zinc Initiated', date: daysAgo(1), completed: true, note: 'Mother trained on clean preparation of ORS' },
    ],
    vitals: { bp: '88/56', pulse: 112, temp: 99.2, weight: 10.5, spo2: 98 },
    symptoms: '5 watery loose motions today, increased thirst, irritability.',
    transcript: 'Bacche ko baar baar patla dast ho raha hai, pyas bahut lag rahi hai.',
    translatedTranscript: 'Child having frequent watery stools, very thirsty.',
    detectedLanguage: 'Hindi',
  },
  {
    id: 'HT-2026-000136',
    patientId: 'P-2026-020',
    patientName: 'Savitri Devi',
    concern: 'Bilateral mature cataract with progressive vision loss',
    priority: 'medium',
    status: 'registered',
    createdDate: daysAgo(9),
    createdBy: 'ASHA Priya',
    timeline: [
      { step: 'Registered', date: daysAgo(9), completed: true, note: 'Identified during village elderly eye screening' },
      { step: 'Acuity Checked', date: daysAgo(9), completed: true, note: 'Finger counting only at 2m' },
      { step: 'Camp Registration', date: daysAgo(9), completed: true, note: 'Listed for free intraocular lens (IOL) surgery camp' },
    ],
    vitals: { bp: '138/82', pulse: 70, temp: 97.8, weight: 56, spo2: 97 },
    symptoms: 'Cloudy vision, unable to recognize faces, difficulty walking unassisted.',
    transcript: 'Dono aankhon se dhundhla dikhta hai, rasta dekhne mein dikkat hoti hai.',
    translatedTranscript: 'Blurry vision in both eyes, difficulty seeing path while walking.',
    detectedLanguage: 'Hindi',
  },
];

export const DEMO_REFERRALS = [
  {
    id: 'REF-2026-001',
    ticketId: 'HT-2026-000125',
    patientId: 'P-2026-002',
    patientName: 'Rajesh Kumar',
    reason: 'Elevated blood sugar (180 mg/dL) and blood pressure (140/90)',
    priority: 'high',
    destination: 'PHC Rampur',
    createdDate: daysAgo(3),
    createdBy: 'ASHA Priya',
    status: 'completed',
  },
  {
    id: 'REF-2026-002',
    ticketId: 'HT-2026-000127',
    patientId: 'P-2026-005',
    patientName: 'Meena Bai',
    reason: 'Severe joint pain, hypertension not controlled with current medication',
    priority: 'high',
    destination: 'District Hospital Hyderabad',
    createdDate: daysAgo(10),
    createdBy: 'ASHA Priya',
    status: 'pending',
  },
  {
    id: 'REF-2026-003',
    ticketId: 'HT-2026-000128',
    patientId: 'P-2026-007',
    patientName: 'Suresh Reddy',
    reason: 'Persistent cough for 3 weeks, possible TB - needs sputum test',
    priority: 'high',
    destination: 'District Hospital Hyderabad',
    createdDate: daysAgo(20),
    createdBy: 'ASHA Priya',
    status: 'in-review',
  },
  {
    id: 'REF-2026-004',
    ticketId: 'HT-2026-000126',
    patientId: 'P-2026-004',
    patientName: 'Ramu Yadav',
    reason: 'Child with persistent fever for 2 days',
    priority: 'medium',
    destination: 'PHC Rampur',
    createdDate: daysAgo(5),
    createdBy: 'ASHA Priya',
    status: 'completed',
  },
  {
    id: 'REF-2026-005',
    ticketId: 'HT-2026-000129',
    patientId: 'P-2026-006',
    patientName: 'Anita Devi',
    reason: 'Week 38 pregnancy with GDM - Plan institutional delivery',
    priority: 'high',
    destination: 'District Hospital Hyderabad',
    createdDate: daysAgo(2),
    createdBy: 'ASHA Priya',
    status: 'accepted',
  },
  {
    id: 'REF-2026-006',
    ticketId: 'HT-2026-000130',
    patientId: 'P-2026-010',
    patientName: 'Manjula Gowda',
    reason: 'Severe Anemia in pregnancy (Hb 7.8 g/dL) - Requires parenteral iron sucrose therapy',
    priority: 'high',
    destination: 'PHC Rampur',
    createdDate: daysAgo(2),
    createdBy: 'ASHA Priya',
    status: 'accepted',
  },
  {
    id: 'REF-2026-007',
    ticketId: 'HT-2026-000132',
    patientId: 'P-2026-013',
    patientName: 'Govind Das',
    reason: 'Chronic productive cough 3+ weeks, night sweats - CBNAAT (GeneXpert) TB testing',
    priority: 'high',
    destination: 'District TB Centre',
    createdDate: daysAgo(3),
    createdBy: 'ASHA Priya',
    status: 'pending',
  },
  {
    id: 'REF-2026-008',
    ticketId: 'HT-2026-000134',
    patientId: 'P-2026-017',
    patientName: 'Devendra Yadav',
    reason: 'Exertional angina with lateral lead ischemia on ECG - Cardiology review',
    priority: 'high',
    destination: 'District Hospital Hyderabad',
    createdDate: daysAgo(7),
    createdBy: 'ASHA Priya',
    status: 'in-review',
  },
  {
    id: 'REF-2026-009',
    ticketId: 'HT-2026-000136',
    patientId: 'P-2026-020',
    patientName: 'Savitri Devi',
    reason: 'Bilateral mature cataract with profound visual loss - Free IOL surgery camp listing',
    priority: 'medium',
    destination: 'District Eye Hospital',
    createdDate: daysAgo(9),
    createdBy: 'ASHA Priya',
    status: 'pending',
  },
];

export const DEMO_FOLLOWUPS = [
  {
    id: 'FU-001',
    patientId: 'P-2026-001',
    patientName: 'Lakshmi Devi',
    reason: 'ANC Week 34 checkup',
    dueDate: daysFromNow(0),
    status: 'due-today',
    type: 'ANC Visit',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-002',
    patientId: 'P-2026-002',
    patientName: 'Rajesh Kumar',
    reason: 'Diabetes and BP follow-up, check medication response',
    dueDate: daysFromNow(4),
    status: 'upcoming',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-003',
    patientId: 'P-2026-006',
    patientName: 'Anita Devi',
    reason: 'Weekly ANC visit - GDM monitoring',
    dueDate: daysFromNow(5),
    status: 'upcoming',
    type: 'ANC Visit',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-004',
    patientId: 'P-2026-004',
    patientName: 'Ramu Yadav',
    reason: 'Check fever resolution',
    dueDate: daysAgo(2),
    status: 'overdue',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-005',
    patientId: 'P-2026-005',
    patientName: 'Meena Bai',
    reason: 'Post district hospital referral check',
    dueDate: daysAgo(3),
    status: 'overdue',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-006',
    patientId: 'P-2026-008',
    patientName: 'Kavitha Prasad',
    reason: 'Allergy follow-up',
    dueDate: daysFromNow(0),
    status: 'due-today',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-007',
    patientId: 'P-2026-003',
    patientName: 'Sita Kumari',
    reason: 'ANC Week 18 checkup',
    dueDate: daysFromNow(14),
    status: 'upcoming',
    type: 'ANC Visit',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-008',
    patientId: 'P-2026-010',
    patientName: 'Manjula Gowda',
    reason: 'Post-IV iron sucrose infusion evaluation & Hb check',
    dueDate: daysFromNow(3),
    status: 'upcoming',
    type: 'ANC Visit',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-009',
    patientId: 'P-2026-011',
    patientName: 'Balram Singh',
    reason: 'Assess COPD inhaler technique, check resting SpO2',
    dueDate: daysFromNow(0),
    status: 'due-today',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-010',
    patientId: 'P-2026-015',
    patientName: 'Vikram Meena',
    reason: 'Verify completion of ACT Malaria course and fever clearance',
    dueDate: daysFromNow(1),
    status: 'upcoming',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-011',
    patientId: 'P-2026-019',
    patientName: 'Chotu Kumar',
    reason: 'Pediatric re-assessment: check hydration & zinc adherence',
    dueDate: daysFromNow(0),
    status: 'due-today',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-012',
    patientId: 'P-2026-013',
    patientName: 'Govind Das',
    reason: 'Collect GeneXpert TB lab results and begin DOTS if positive',
    dueDate: daysAgo(1),
    status: 'overdue',
    type: 'Follow-up',
    assignedTo: 'ASHA Priya',
  },
  {
    id: 'FU-013',
    patientId: 'P-2026-016',
    patientName: 'Shanti Devi',
    reason: 'PNC Day 28 Visit & Infant Immunization check (BCG, OPV, Hep B)',
    dueDate: daysFromNow(14),
    status: 'upcoming',
    type: 'ANC Visit',
    assignedTo: 'ASHA Priya',
  },
];

export const DEMO_FACILITIES = [
  {
    id: 'FAC-001',
    name: 'PHC Rampur',
    type: 'Primary Health Centre',
    address: 'Main Road, Rampur Village',
    distance: '2 km',
    phone: 'DEMO - Not a real number',
    services: ['General OPD', 'ANC', 'Immunization', 'Basic Lab'],
    doctors: ['Dr. Sharma', 'Dr. Reddy'],
  },
  {
    id: 'FAC-002',
    name: 'Sub-Centre Sundernagar',
    type: 'Sub-Centre',
    address: 'Village Road, Sundernagar',
    distance: '0.5 km',
    phone: 'DEMO - Not a real number',
    services: ['Basic Healthcare', 'ANC', 'Immunization'],
    doctors: [],
  },
  {
    id: 'FAC-003',
    name: 'District Hospital',
    type: 'District Hospital',
    address: 'NH Road, District HQ',
    distance: '25 km',
    phone: 'DEMO - Not a real number',
    services: ['Emergency', 'Surgery', 'Maternity', 'Lab', 'Radiology', 'TB Screening'],
    doctors: ['Multiple specialists available'],
  },
  {
    id: 'FAC-004',
    name: 'Community Health Centre',
    type: 'Government Hospital',
    address: 'Block Road, Block HQ',
    distance: '12 km',
    phone: 'DEMO - Not a real number',
    services: ['OPD', 'Emergency', 'Maternity', 'Lab'],
    doctors: ['Dr. Patel', 'Dr. Singh'],
  },
];

export const DEMO_EDUCATION = [
  {
    id: 'EDU-001',
    category: 'Maternal Health',
    title: 'Importance of Regular ANC Visits',
    description: 'Learn about the recommended schedule for antenatal care visits and what to expect during each visit.',
    content: 'Regular ANC visits help monitor the health of both mother and baby. WHO recommends at least 8 contacts during pregnancy. Early registration helps identify and manage complications.',
    languages: ['English', 'Hindi', 'Telugu'],
    hasAudio: true,
  },
  {
    id: 'EDU-002',
    category: 'Nutrition',
    title: 'Balanced Diet During Pregnancy',
    description: 'Nutritional requirements during pregnancy and how to meet them with locally available foods.',
    content: 'During pregnancy, the body needs extra iron, calcium, folic acid and protein. Locally available foods like green leafy vegetables, dairy products, pulses and fruits can help meet these needs.',
    languages: ['English', 'Hindi', 'Telugu'],
    hasAudio: true,
  },
  {
    id: 'EDU-003',
    category: 'Vaccination',
    title: 'Child Immunization Schedule',
    description: 'Complete immunization schedule for children from birth to 5 years as per national guidelines.',
    content: 'Timely vaccination protects children from dangerous diseases. The national immunization schedule includes BCG, OPV, Hepatitis B, Pentavalent, Rotavirus, PCV, MR, JE and DPT vaccines.',
    languages: ['English', 'Hindi', 'Telugu'],
    hasAudio: true,
  },
  {
    id: 'EDU-004',
    category: 'Sanitation',
    title: 'Clean Water and Hygiene Practices',
    description: 'Simple steps for water purification and hygiene to prevent waterborne diseases.',
    content: 'Boiling water for 1 minute kills most harmful bacteria. Regular handwashing with soap, especially before meals and after using the toilet, prevents many diseases.',
    languages: ['English', 'Hindi', 'Telugu'],
    hasAudio: false,
  },
  {
    id: 'EDU-005',
    category: 'Seasonal Health',
    title: 'Preventing Dengue and Malaria',
    description: 'Steps to prevent mosquito-borne diseases during monsoon season.',
    content: 'Remove stagnant water around the house. Use mosquito nets while sleeping. Wear full-sleeve clothing. Seek medical attention immediately if you have high fever with body pain.',
    languages: ['English', 'Hindi', 'Telugu'],
    hasAudio: true,
  },
  {
    id: 'EDU-006',
    category: 'Maternal Health',
    title: 'Danger Signs During Pregnancy',
    description: 'Warning signs that need immediate medical attention during pregnancy.',
    content: 'Seek immediate help if you notice: severe headache, blurred vision, swelling of face/hands, vaginal bleeding, reduced baby movements, high fever, or severe abdominal pain.',
    languages: ['English', 'Hindi', 'Telugu'],
    hasAudio: true,
  },
];

export const DEMO_USERS = {
  asha: { id: 'U-001', name: 'Priya Kumari', role: 'asha', phone: '98XXXXXXX1', area: 'Rampur & Sundernagar', phc: 'PHC Rampur' },
  doctor: { id: 'U-002', name: 'Dr. Sharma', role: 'doctor', phone: '98XXXXXXX2', specialization: 'General Medicine', phc: 'PHC Rampur' },
  patient: { id: 'U-003', name: 'Lakshmi Devi', role: 'patient', phone: '9876XXXX01', patientId: 'P-2026-001' },
  admin: { id: 'U-004', name: 'Vikram Singh', role: 'admin', phone: '98XXXXXXX4', area: 'District HQ' },
};

export function getPatientById(id) {
  return DEMO_PATIENTS.find(p => p.id === id) || null;
}

export function getTicketsByPatient(patientId) {
  return DEMO_HEALTH_TICKETS.filter(t => t.patientId === patientId);
}

export function getReferralsByPatient(patientId) {
  return DEMO_REFERRALS.filter(r => r.patientId === patientId);
}

export function getFollowupsByPatient(patientId) {
  return DEMO_FOLLOWUPS.filter(f => f.patientId === patientId);
}

export function searchPatients(query) {
  if (!query) return DEMO_PATIENTS;
  const q = query.toLowerCase();
  return DEMO_PATIENTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.id.toLowerCase().includes(q) ||
    p.phone.toLowerCase().includes(q) ||
    p.village.toLowerCase().includes(q)
  );
}

export function getTicketById(id) {
  return DEMO_HEALTH_TICKETS.find(t => t.id === id) || null;
}
